/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Number_guessing_programm;
import java.util.Scanner;

/**
 *
 * @author user
 */
public class Number_guess {

    public static void main(String[] args) { //main method
        Main_number_guess main_number_guess = new Main_number_guess();//createda new object of class Number_guess
        main_number_guess.number_guess();//object calling the number_guess method

    }
}

class Main_number_guess {

    public void number_guess() { //number_guess method
        Scanner sobj1 = new Scanner(System.in); //new object of class scanner
        int number = 1 * (int) (10 * Math.random()); //Using the Math method to pick a random number from 10
        System.out.println("guess th number : \n"); //User prompt
        int trial = 5;
        for (int iterator = 0; iterator < trial; iterator++) { //trials level
            int User_num = sobj1.nextInt(); //User input
            if (User_num != number) { //using if statement to check if the user input is not equals to the random number generated by the Math method
                System.out.println("oops try again you have use " + iterator + " of your trials");
            } else {
                System.out.println("congratulations you got the lucky number right " + number);
                break;
            }

        }

    }

}
